import PantallaFormularioInformacionVehiculoCristal from "./pantalla-formulario-informacion-vehiculo-cristal-componente/PantallaFormularioInformacionVehiculoCristal";

export default PantallaFormularioInformacionVehiculoCristal;
